name:                trialChain
version:             0.1.0.0
github:              "githubuser/trialChain"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trialChain#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- cryptohash
- directory
- bytestring
- servant-server
- random
- text
- time
- wai
- warp

library:
  source-dirs: src

executables:
  trialChain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - trialChain

tests:
  trialChain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - base
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-types
    - trialChain
    - wai-extra
